export enum StudyClass {
    PRIMARY = 'PRIMARY',
    MIDDLE_SCHOOL = 'MIDDLE_SCHOOL',
    HIGH_SCHOOL = 'HIGH_SCHOOL',
    BACHELOR1 = 'BACHELOR1' ,
    BACHELOR2 = 'BACHELOR2',
    MASTER1 = 'MASTER1',
    MASTER2 = 'MASTER2',
    TRAINING = 'TRAINING',
}
